#!/bin/bash
source `which virtualenvwrapper.sh`
mkvirtualenv qr
workon qr
python3 -m pip install imutils
python3 -m pip install pyzbar
python3 -m pip install opencv-python
python3 -m pip install numpy
echo  QR-Barcode-Reader has been installed, virtual environment qr has been filled with the necessary dependencies.
echo Refer README.txt for further instructions 
